version: "3"
services:
  mountebank:
    container_name: mb
    image: jkris/mountebank:latest
    volumes:
    - ./imposters:/imposters
    ports:
    - 2525:2525
    - 5550:5550
    command: --configfile /imposters/imposters.ejs --allowInjection
    
